<?php get_header(); ?>

<!-- Main Content -->
      <main class="main-content">
        <div class="hero-text">
          <h1 class="main-headline">
            <span class="line">YOUR DATA RUNS</span>
            <span class="line">THE WORLD</span>
          </h1>
          
          <div class="scroll-indicator">SCROLL DOWN</div>
        </div>

        <!-- Categories Section -->
        <section class="categories-section">
          <div class="category-cards" id="categoryCards">
            <!-- Cards will be generated by JavaScript -->
          </div>
        </section>

        <!-- CTA Button -->
        <button class="cta-button" id="ctaButton">
          CLICK ME
        </button>
      </main>
    </div>
    
<!-- <section class="hero">
    <h1><?php bloginfo('name'); ?></h1>
    <p><?php bloginfo('description'); ?></p>
    <button onclick="document.querySelector('.posts').scrollIntoView({behavior: 'smooth'})">
        See Latest Posts
    </button>
</section>

<section class="posts">
    <h2>Latest Posts</h2>
    <div class="post-list">
        <?php if (have_posts()) : while (have_posts()) : the_post(); ?>
            <article>
                <h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3>
                <p><?php echo wp_trim_words(get_the_excerpt(), 20); ?></p>
            </article>
        <?php endwhile; else: ?>
            <p>No posts found.</p>
        <?php endif; ?>
    </div>
</section> -->

<?php get_footer(); ?>
